// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://jsgbqrrlpxzzqubtzrkk.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzZ2JxcnJscHh6enF1YnR6cmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjkzMjAsImV4cCI6MjA2NTgwNTMyMH0.AO5Rwx6UREFdJoxNoEJmYxf6C3KDt_uyAspKKSQE4t4";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);